" Generated by vim-plug
" Sat 22 Oct 00:02:22 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-session'].commit = '39319bf7ad15a1881f180fa7c14bf6703775035e'
silent! let g:plugs['coc.nvim'].commit = 'd0fa7acd233d76585daf9ce0b74ad1112591e271'
silent! let g:plugs['copilot.vim'].commit = '8ba151a20bc1d7a5c72e592e51bfc925d5bbb837'
silent! let g:plugs['fzf'].commit = '07da058eae6f26de4cbe08c48563154e775f6183'
silent! let g:plugs['fzf.vim'].commit = '9ceac718026fd39498d95ff04fa04d3e40c465d7'
silent! let g:plugs['gitsigns.nvim'].commit = '9787c94178b4062f30d2f06b6d52984217196647'
silent! let g:plugs['hop.nvim'].commit = '9b2df92594f04d729f3e0f2eb7a5cd691c5c23fa'
silent! let g:plugs['impatient.nvim'].commit = 'b842e16ecc1a700f62adb9802f8355b99b52a5a6'
silent! let g:plugs['lazygit.nvim'].commit = '9c73fd69a4c1cb3b3fc35b741ac968e331642600'
silent! let g:plugs['lualine.nvim'].commit = 'edca2b03c724f22bdc310eee1587b1523f31ec7c'
silent! let g:plugs['nvim-autopairs'].commit = '4fc96c8f3df89b6d23e5092d31c866c53a346347'
silent! let g:plugs['nvim-comment'].commit = 'e9ac16ab056695cad6461173693069ec070d2b23'
silent! let g:plugs['nvim-dap'].commit = '6b12294a57001d994022df8acbe2ef7327d30587'
silent! let g:plugs['nvim-dap-go'].commit = 'c2902bb96c45e872d947d7e174775e652439add4'
silent! let g:plugs['nvim-dap-ui'].commit = '1cd4764221c91686dcf4d6b62d7a7b2d112e0b13'
silent! let g:plugs['nvim-dap-virtual-text'].commit = '2971ce3e89b1711cc26e27f73d3f854b559a77d4'
silent! let g:plugs['nvim-tree.lua'].commit = '875d38e52cc4367bad10e648a906a6bd73b3691c'
silent! let g:plugs['nvim-treesitter'].commit = '42b482fd56c8562efda0b4b8dd962e815fc4b161'
silent! let g:plugs['nvim-ts-autotag'].commit = 'fdefe46c6807441460f11f11a167a2baf8e4534b'
silent! let g:plugs['playground'].commit = 'e6a0bfaf9b5e36e3a327a1ae9a44a989eae472cf'
silent! let g:plugs['rasmus.nvim'].commit = 'd1ac6152b3fb4e8a1be372d344fc753e5fbb88ba'
silent! let g:plugs['templ.vim'].commit = '2d1ca014c360a46aade54fc9b94f065f1deb501a'
silent! let g:plugs['undotree'].commit = 'bd60cb564e3c3220b35293679669bb77af5f389d'
silent! let g:plugs['vim-cool'].commit = 'e797f80545073f9e5b0689b91633feda7bb17cc2'
silent! let g:plugs['vim-easy-align'].commit = '12dd6316974f71ce333e360c0260b4e1f81169c3'
silent! let g:plugs['vim-lastplace'].commit = 'cef9d62165cd26c3c2b881528a5290a84347059e'
silent! let g:plugs['vim-paper'].commit = 'edfb0acc8b43989cdf26a43dea38488ebed057a4'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-startuptime'].commit = '1a5fe7b6275d8f62647969012dcd5bcceb2cebc6'
silent! let g:plugs['vim-surround'].commit = 'bf3480dc9ae7bea34c78fbba4c65b4548b5b1fea'
silent! let g:plugs['vim-test'].commit = 'e7150de777ef0c81a015972e4feb56c4b3137efd'
silent! let g:plugs['vim-visual-multi'].commit = '724bd53adfbaf32e129b001658b45d4c5c29ca1a'

PlugUpdate!

